### ISSUE TITLE
Change Co-opsUK Mykomap About text

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#11]
About the Co-operatives UK Open Data map

This [Mykomap](https://digitalcommons.coop/mykomaps/) has been created by the [Digital Commons Co-operative](https://digitalcommons.coop) using data published by [Co-ops UK](https://www.uk.coop) under the Open Data Commons Attribution Licence (ODC-By v 1.0.) By accessing the dataset you are agreeing to accept this license.

The original data can be found at https://www.uk.coop/resources/open-data
The data was last updated for Q4 2022. 
The license can be viewed at https://opendatacommons.org/licenses/by/1-0/

**Comment by wu-lee** [comment]
Now done, dev-mode map redeployed.

**Comment by ColmDC** [comment]
How is the text in the bottom of the about box generated? 
"The source data of the content is here:

    Coops UK 2

Technical information about the technology behind this map and directory can be found here:

https://github.com/SolidarityEconomyAssociation/sea-map/wiki"

I was thinking of dropping this until we had a better vis of the raw data and better description of the project in the github wiki.

**Comment by wu-lee** [comment]
The second half of the about text is hard-wired boiler-plate, with specific bits inserted.  The boilerplate text is localised, and the links are inserted, plus titles from the vocab/data where available.

**Comment by ColmDC** [comment]
>Therefore this part of the about text is common to all maps.
Can we remove it? Just leave the version #

**Comment by wu-lee** [comment]
I could remove it.  Infer that you want this to also disappear on ICA, DotCoop and the rest when they get upgraded?

**Comment by ColmDC** [comment]
Yes. When we have made some decent public friendly pages on Github and overhauled the html views of the data we can re-introduce.

**Comment by ColmDC** [comment]
Once this section has been removed from the about, we can push to prod!

**Comment by wu-lee** [comment]
Ok, that section's been removed, and the map redeployed.

**Comment by wu-lee** [comment]
(On dev, will redeploy to prod on a thumb's up)

**Comment by wu-lee** [comment]
This is now redeployed.

**Comment by ColmDC** [comment]
Can't see it. https://prod.coopsuk.solidarityeconomy.coop/ is still sea-map@1.3.5_a9fbc7c

**Comment by wu-lee** [comment]
Sorry - try again. Deployment parameters set wrong (need to redeploy dev-1 now!)

**Comment by ColmDC** [comment]
>The data was last updated for Q4 2022.
It should read Q2 2022

**Comment by ColmDC** [comment]
I also just noticed that the hyperlinks did not make it into the about panel.
