### ISSUE TITLE
Support Geocoding of co-ops in Northern Ireland

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#17]
**Is your feature request related to a problem? Please describe.**
No co-ops based in Northern Ireland appear on the [Co-ops UK Map](https://coopsuk.solidarityeconomy.coop)

**Describe the solution you'd like**
Co-ops UK data processing uses a different method of geocoding from all later projects. It used an ordnance survey system that returns long lat by postcode, which does not support postcodes from Northern Ireland. It needs to support them. 

Change the system for Co-ops UK data to use the coder we use for other projects.

**Describe alternatives you've considered**
There may be another OS solution which now includes NI postcodes but a v quick look did not find any.

**Additional context**

**Comment by wu-lee** [comment]
This is now deployed. You should see pins in both Northern Ireland and Jersey. I needed to work around this first however. https://github.com/DigitalCommons/coopsuk/issues/21#issuecomment-1589722435
