### ISSUE TITLE
Rename sea-map repo as Mykomap

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/coopsuk#8]
As sea-map is a dependency of all the map projects, renaming it will probably need all these maps to change their dependencies after the name-change.

Internally, the name is used in a lot of places, and may need updating there too.

**Comment by ColmDC** [comment]
This has already been done, but perhaps this ticket is to test for any consequences? @wu-lee

**Comment by ColmDC** [comment]
Happy to close this @wu-lee

**Comment by wu-lee** [comment]
This has been done as part of mykomap v3.0.0, and the coops-uk map has been adapted to use it. Tests and deployment also corrected to work. 

Currently live on https://dev.coopsuk.solidarityeconomy.coop/
