### ISSUE TITLE
Update dialog configuration for Co-ops UK map to display Base Membership

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/coopsuk#9]
## Description
There is more data being published about co-ops uk co-ops than being displayed in the dialog. 
Base Membership Type is one. See if there are other and add to configuration. List any others added in this ticket.

## Acceptance Criteria
Choose a couple of co-ops you are familiar with. Check what data is provided for them in the raw open data provided by Co-ops UK. 

In the the latest version of https://dev.coopsuk.solidarityeconomy.coop/ search for the co-op and check that Base Membership Type is now being displayed and is correct in the dialog. Check for any other fields that this ticked says  were added.

**Comment by wu-lee** [comment]
CUK Sector (simplified) and SIC Section have already been added to the pop-up.

Base membership type added too now (although the title is "Typology" because that's the name embedded in the BMT data vocabualry). Deployed on the dev server.

There are no other categories to add unless you want the fine grained and gruesome 6 level SIC code system to be shown. 

standard.csv fields are:
```
  1: Identifier
  2: Name
  3: Description
  4: Organisational Structure
  5: Primary Activity
  6: Activities
  7: Street Address
  8: Locality
  9: Region
 10: Postcode
 11: Country ID
 12: Territory ID
 13: Website
 14: Phone
 15: Email
 16: Twitter
 17: Facebook
 18: Companies House Number
 19: Qualifiers
 20: Membership Type
 21: Latitude
 22: Longitude
 23: Geo Container
 24: Geo Container Latitude
 25: Geo Container Longitude
 26: Sector
 27: SIC Section
 28: SIC Code
 29: Ownership Classification
 30: Legal Form
```

Original CUK data fields are:
```
  1: CUK Organisation ID
  2: Registered Number
  3: Registrar
  4: Registered Name
  5: Trading Name
  6: Legal Form
  7: Registered Street
  8: Registered City
  9: Registered State/Province
 10: Registered Postcode
 11: UK Nation
 12: SIC Code
 13: SIC section
 14: SIC code  - level 2
 15: SIC code  - level 2 description
 16: SIC code  - level 3
 17: SIC code  - level 3 description
 18: SIC code  - level 4
 19: SIC code  - level 4 description
 20: SIC code  - level 5
 21: SIC code  - level 5 description
 22: Sector - Simplified, High Level
 23: Ownership Classification
 24: Registered Status
 25: Incorporation Date
 26: Dissolved Date
 27: Website
 28: Registered Admin County Code
 29: Registered Admin County Name
 30: Registered Admin District Code
 31: Registered Admin District Name
 32: Registered Admin Ward Code
 33: Registered Admin Ward Name
 34: Registered Constituency Code
 35: Registered Constituency Name
 36: Registered LSOA Name
 37: Registered MSOA Name
 38: Registered Parish Code
 39: Registered Parish Name
```

**Comment by wu-lee** [comment]
If you want to check a case with the max number of these categories, try Littleton & Badsey Growers. This should have a Sector, SIC Section, Typology, Structure Type and Main Activity.  Currently no CUK organisations have any Secondary Activities

**Comment by ColmDC** [comment]
> This should have a Sector, SIC Section, Typology, Structure Type and Main Activity

Typology is only one missing.

**Comment by ColmDC** [comment]
> .. Structure Type 

It's Organisation Structure should be OS50 rather than OS10

**Comment by ColmDC** [comment]
No Multi stakeholder or housing co-ops seem to have been allocated correctly.

**Comment by wu-lee** [comment]
> > This should have a Sector, SIC Section, Typology, Structure Type and Main Activity
> 
> Typology is only one missing.

Should be back now. Some later work clobbered this, recovered it.

**Comment by wu-lee** [comment]
Org Struct field values are missing from the popup when they shouldn't be... see L&B Growers example above.

**Comment by wu-lee** [comment]
> > .. Structure Type
> 
> It's Organisation Structure should be OS50 rather than OS10

> No Multi stakeholder or housing co-ops seem to have been allocated correctly.

These look to be consequences of the incorrect mapping mentioned in  https://github.com/digitalcommons/technology-and-infrastructure/issues/79. Correct?

If so, I think this issue can be closed, and those points dealt with there.
